/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "X_aliases.h"
#include "X.h"
#include "Mux.h"
#include "Y_aliases.h"
#include "Y.h"
#include "sw_aliases.h"
#include "sw.h"
#include "PWM.h"
#include "Clock.h"
#include "PWM2.h"
#include "S1_aliases.h"
#include "S1.h"
#include "S2_aliases.h"
#include "S2.h"
#include "S4_aliases.h"
#include "S4.h"
#include "S5_aliases.h"
#include "S5.h"
#include "Enable_aliases.h"
#include "Enable.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC_Bypass_aliases.h"
#include "ADC_Bypass.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

